@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RAbWFpbC5jb20iLCJpZCI6MSwiaWF0IjoxNjU3MTk1NDUwfQ.33cYGzGxC2LnAeym392om_qVEunNgAqIOFmY_s12gmQ

GET http://localhost:3001/api/blogs

####
GET http://localhost:3001/api/blogs?search=author

####
POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: Bearer {{token}}

{
  "author": "test POST",
  "url": "test.url.fi",
  "title": "Test POST command"
}

####
DELETE http://localhost:3001/api/blogs/1
Authorization: Bearer {{token}}

####
PUT http://localhost:3001/api/blogs/2
content-type: application/json

{
  "likes": 2
}

#### USERS 
POST http://localhost:3001/api/users
content-type: application/json

{
  "username": "notEmail",
  "name": "tester test"
}

####
PUT http://localhost:3001/api/users/test12@mail.com
content-type: application/json

{
  "username": "test@mail.com"
}

####
GET http://localhost:3001/api/users/

### LOGIN
POST http://localhost:3001/api/login/
content-type: application/json

{
  "username": "test@mail.com",
  "password": "secret"
}

#### AUTHORS
GET http://localhost:3001/api/authors